name: preprocessing

on:
  push:
    paths:
      - "automate_Aprilia-Melani.py"
      - "dataset/**"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pandas numpy scikit-learn

    - name: Run preprocessing script
      run: |
        python automate_Aprilia-Melani.py

    - name: Upload cleaned dataset
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-dataset
        path: prepocessing/diabetes_preprocessing.csv
